#!/bin/bash
# nxmc reads its settings from nxmc.properties on the classpath — an env var
# alone is not enough, and without the file the console falls back to
# 127.0.0.1:4701 and fails with "Connection refused". Generate the file from
# the environment before Tomcat starts.
set -euo pipefail

PROPS=/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/nxmc.properties

{
  echo "# Generated by docker-entrypoint.sh — edits are overwritten on restart."
  echo "server=${NETXMS_SERVER:-netxms}"
  if [ -n "${NXMC_LOGIN:-}" ]; then
    echo "login=${NXMC_LOGIN}" # pre-fills the login name on the sign-in page
  fi
  if [ -n "${NXMC_LANGUAGE:-}" ]; then
    echo "nxmc.language=${NXMC_LANGUAGE}" # e.g. fr, en
  fi
} > "$PROPS"

echo "[entrypoint] nxmc.properties -> server=${NETXMS_SERVER:-netxms}"

# nxmc ships logback.xml with the root logger at DEBUG — hundreds of lines per
# startup and a line per perspective switch afterwards — and a rolling file
# appender pointing at ${nxmc.logfile}, which nothing defines here, so it
# creates a file literally named "nxmc.logfile_IS_UNDEFINED". Replace it with a
# console-only config at NXMC_LOG_LEVEL.
cat > /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/logback.xml <<EOF
<!-- Generated by docker-entrypoint.sh — edits are overwritten on restart. -->
<configuration>
   <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
      <layout class="ch.qos.logback.classic.PatternLayout">
         <Pattern>%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n</Pattern>
      </layout>
   </appender>
   <root level="${NXMC_LOG_LEVEL:-info}">
      <appender-ref ref="Console"/>
   </root>
</configuration>
EOF

echo "[entrypoint] logback root level -> ${NXMC_LOG_LEVEL:-info} (console only)"

exec "$@"
