#!/bin/bash
# Renders /etc/netxmsd.conf from the environment, initializes the database on
# first start, then runs netxmsd in the foreground.
set -euo pipefail

log() { echo "[entrypoint] $*"; }

CONF=/etc/netxmsd.conf
AGENT_CONF=/etc/nxagentd.conf

DB_DRIVER=${NETXMS_DB_DRIVER:-pgsql}
DB_HOST=${NETXMS_DB_HOST:-netxms-db}
DB_PORT=${NETXMS_DB_PORT:-5432}
DB_NAME=${NETXMS_DB_NAME:-netxms}
DB_LOGIN=${NETXMS_DB_LOGIN:-netxms}
DB_PASSWORD=${NETXMS_DB_PASSWORD:-netxms}
ADMIN_PASSWORD=${NETXMS_ADMIN_PASSWORD:-netxms}
WEBAPI_PORT=${NETXMS_WEBAPI_PORT:-8000}
DEBUG_LEVEL=${NETXMS_DEBUG_LEVEL:-1}
START_AGENT=${NETXMS_START_AGENT:-true}

# ─────────────────────────── netxmsd.conf ───────────────────────────
# Regenerated on every start so the container follows the environment. Mount
# your own file over /etc/netxmsd.conf and set NETXMS_KEEP_CONFIG=true to keep it.
write_config() {
  if [ "${NETXMS_KEEP_CONFIG:-false}" = "true" ] && [ -f "$CONF" ]; then
    log "NETXMS_KEEP_CONFIG=true — using existing $CONF"
    return
  fi

  {
    echo "# Generated by docker-entrypoint.sh — edits are overwritten on restart."
    echo "LogFile=/var/log/netxmsd"
    echo "DebugLevel=${DEBUG_LEVEL}"
    if [ "$DB_DRIVER" = "sqlite" ] || [ "$DB_DRIVER" = "sqlite3" ]; then
      echo "DBDriver=sqlite.ddr"
      echo "DBName=${NETXMS_DB_FILE:-/var/lib/netxms/netxms.db}"
    else
      echo "DBDriver=${DB_DRIVER}.ddr"
      echo "DBServer=${DB_HOST}:${DB_PORT}"
      echo "DBName=${DB_NAME}"
      echo "DBLogin=${DB_LOGIN}"
      echo "DBPassword=${DB_PASSWORD}"
    fi
    # Web API (REST v1) — served by the webapi module inside netxmsd.
    echo "Module=webapi"
    echo ""
    echo "*WEBAPI"
    echo "Enable=yes"
    echo "Address=0.0.0.0"
    echo "Port=${WEBAPI_PORT}"
    echo "TLSEnable=no"
  } > "$CONF"
  chmod 600 "$CONF"
  log "wrote $CONF (driver=${DB_DRIVER}, web API port ${WEBAPI_PORT})"
}

# ─────────────────────────── database ───────────────────────────
is_sqlite() {
  [ "$DB_DRIVER" = "sqlite" ] || [ "$DB_DRIVER" = "sqlite3" ]
}

wait_for_db() {
  if is_sqlite; then
    return 0
  fi
  log "waiting for ${DB_HOST}:${DB_PORT}…"
  for _ in $(seq 1 60); do
    if (exec 3<>"/dev/tcp/${DB_HOST}/${DB_PORT}") 2>/dev/null; then
      exec 3<&- 2>/dev/null || true
      log "database is reachable"
      return 0
    fi
    sleep 2
  done
  log "ERROR: ${DB_HOST}:${DB_PORT} unreachable after 120s"
  return 1
}

init_db() {
  # `get` reads the server config table, so it succeeds only against an
  # initialized schema — a cheap "is this a first start?" probe.
  if nxdbmgr -q -m -c "$CONF" get 'SchemaVersion' >/dev/null 2>&1; then
    log "database schema present — running pending upgrades"
    nxdbmgr -q -c "$CONF" upgrade || log "WARNING: nxdbmgr upgrade failed (continuing)"
    return 0
  fi

  # The schema type has to be passed explicitly — nxdbmgr cannot deduce it from
  # a "<driver>.ddr" DBDriver value.
  local db_type
  if is_sqlite; then db_type=sqlite; else db_type=$DB_DRIVER; fi

  log "initializing database schema (${db_type})…"
  if ! nxdbmgr -q -c "$CONF" init "$db_type" -p "$ADMIN_PASSWORD"; then
    log "ERROR: nxdbmgr init failed"
    return 1
  fi
  # nxdbmgr keeps the seeded UF_CHANGE_PASSWORD flag (0x08) on "admin" even when
  # the password is set with -p: the account would then accept exactly one login
  # and answer 403 (RCC_PASSWORD_EXPIRED) afterwards, breaking the ETL, which
  # logs in on every poll. Clear the flag and restore the grace logins.
  cat > /tmp/nxms-admin.sql <<'SQL'
UPDATE users SET flags = flags & ~8, grace_logins = 5, auth_failures = 0 WHERE name = 'admin';
SQL
  nxdbmgr -q -c "$CONF" batch /tmp/nxms-admin.sql \
    || log "WARNING: could not clear the admin password-change flag"
  rm -f /tmp/nxms-admin.sql

  log "database initialized (admin password taken from NETXMS_ADMIN_PASSWORD)"
}

# netxmsd takes a lock row in the database and releases it when it shuts down.
# A container that is killed rather than stopped — a host reboot, an OOM kill —
# never gets there, and the next start refuses with "Database is already locked
# by another NetXMS server instance", needing a manual `nxdbmgr unlock`. Exactly
# one server ever uses this database, so a lock found at startup is stale by
# definition. (Point a second netxmsd at the same database and this would let
# both run; don't.)
unlock_db() {
  local output
  output=$(yes | nxdbmgr -c "$CONF" unlock 2>&1) || true
  case "$output" in
  *"lock removed"*) log "cleared a stale database lock left by an unclean stop" ;;
  esac
}

# ─────────────────────────── local agent ───────────────────────────
# netxmsd always creates a management node for itself, named after the container
# hostname; the local agent is what turns it into an actually monitored node
# (agent version, platform, DCIs) — the same role zabbix-agent plays for Zabbix.
# Set `hostname:` in compose to give that node a stable, matchable name.
start_agent() {
  [ "$START_AGENT" = "true" ] || return 0
  if [ ! -f "$AGENT_CONF" ]; then
    {
      echo "# Generated by docker-entrypoint.sh"
      echo "MasterServers=127.0.0.1"
      echo "LogFile=/var/log/nxagentd"
      echo "FileStore=/var/lib/netxms/agent"
    } > "$AGENT_CONF"
  fi
  mkdir -p /var/lib/netxms/agent
  nxagentd -d -c "$AGENT_CONF"
  log "local NetXMS agent started"
}

# ─────────────────────────── main ───────────────────────────
if [ "${1:-netxmsd}" = "netxmsd" ]; then
  write_config
  wait_for_db
  init_db
  unlock_db
  start_agent
  log "starting netxmsd"
  exec netxmsd -c "$CONF" -q
fi

exec "$@"
