#!/bin/bash
# Configures Centreon from the environment, runs its install wizard
# non-interactively on first start, then supervises the central's daemons with
# Apache in the foreground.
set -euo pipefail

log() { echo "[entrypoint] $*"; }
die() { echo "[entrypoint] ERROR: $*" >&2; exit 1; }

DB_HOST=${CENTREON_DB_HOST:-centreon-db}
DB_PORT=${CENTREON_DB_PORT:-3306}
DB_ROOT_USER=${CENTREON_DB_ROOT_USER:-root}
DB_ROOT_PASSWORD=${CENTREON_DB_ROOT_PASSWORD:-centreon_db_root}
DB_USER=${CENTREON_DB_USER:-centreon}
DB_PASSWORD=${CENTREON_DB_PASSWORD:-centreon_db_pass}
DB_CONFIGURATION=${CENTREON_DB_NAME:-centreon}
DB_STORAGE=${CENTREON_DB_STORAGE_NAME:-centreon_storage}
ADMIN_PASSWORD=${CENTREON_ADMIN_PASSWORD:-Centreon!2024}
ADMIN_EMAIL=${CENTREON_ADMIN_EMAIL:-admin@centreon.local}
ADMIN_FIRSTNAME=${CENTREON_ADMIN_FIRSTNAME:-Centreon}
ADMIN_LASTNAME=${CENTREON_ADMIN_LASTNAME:-Admin}
TIMEZONE=${TZ:-Europe/Paris}
INSTALL_MODULES=${CENTREON_INSTALL_MODULES:-true}
APPLY_CONFIG=${CENTREON_APPLY_CONFIG:-true}
START_MONITORING=${CENTREON_START_MONITORING:-true}
MONITOR_SELF=${CENTREON_MONITOR_SELF:-true}

WWW=/usr/share/centreon/www
INSTALL_DIR=$WWW/install
INSTALL_URL=http://127.0.0.1/centreon/install
CENTREON_CONF=/etc/centreon/centreon.conf.php
COOKIE_JAR=/tmp/centreon-install-cookies
LOG_DIR=/var/log/centreon-docker

mysql_root() {
  mariadb -h "$DB_HOST" -P "$DB_PORT" -u "$DB_ROOT_USER" "-p$DB_ROOT_PASSWORD" "$@"
}

# ─────────────────────────── PHP / Apache ───────────────────────────
# date.timezone must be set for Centreon's own prerequisite check, and the
# install imports several MB of SQL, which outlives the stock 30s limit.
configure_php() {
  local ini
  for ini in /etc/php/8.2/fpm/conf.d /etc/php/8.2/cli/conf.d; do
    [ -d "$ini" ] || continue
    {
      echo "; Generated by docker-entrypoint.sh — edits are overwritten on restart."
      echo "date.timezone = ${TIMEZONE}"
      echo "max_execution_time = 0"
      echo "max_input_time = -1"
      echo "memory_limit = ${CENTREON_PHP_MEMORY_LIMIT:-512M}"
    } > "$ini/99-centreon-docker.ini"
  done
  log "PHP configured (timezone ${TIMEZONE})"
}

start_php_fpm() {
  mkdir -p /run/php /var/lib/php/sessions
  chown www-data:www-data /var/lib/php/sessions
  /usr/sbin/php-fpm8.2 --daemonize
  log "php-fpm started"
}

wait_for_http() {
  local url=$1
  for _ in $(seq 1 60); do
    curl -fs -o /dev/null -m 5 "$url" && return 0
    sleep 1
  done
  return 1
}

# The configuration directories are volumes, and a volume keeps the numeric
# uid/gid it was first populated with — which stops matching when the image is
# rebuilt and the packages happen to claim different ids. Everything Centreon
# writes goes through these directories, so re-assert their ownership by name.
fix_volume_ownership() {
  local entry directory owner
  for entry in \
    "/etc/centreon:centreon" \
    "/etc/centreon-gorgone:centreon-gorgone" \
    "/etc/centreon-engine:centreon-engine" \
    "/etc/centreon-broker:centreon-broker" \
    "/var/lib/centreon:centreon" \
    "/var/lib/centreon-engine:centreon-engine" \
    "/var/lib/centreon-broker:centreon-broker" \
    "/var/log/centreon:centreon" \
    "/var/log/centreon-engine:centreon-engine" \
    "/var/log/centreon-broker:centreon-broker" \
    "/var/log/centreon-gorgone:centreon-gorgone"; do
    directory=${entry%%:*}
    owner=${entry##*:}
    [ -d "$directory" ] || continue
    chown -R "${owner}:${owner}" "$directory"
  done
  log "configuration directory ownership checked"
}

# ─────────────────────────── database ───────────────────────────
wait_for_db() {
  log "waiting for ${DB_HOST}:${DB_PORT}…"
  for _ in $(seq 1 90); do
    if mysql_root -e 'SELECT 1' >/dev/null 2>&1; then
      log "database is reachable"
      return 0
    fi
    sleep 2
  done
  die "${DB_HOST}:${DB_PORT} unreachable (or wrong root password) after 180s"
}

# The wizard grants the Centreon database user on the *IP* the container had
# when it ran (createDbUser.php reads it from information_schema.processlist),
# and a container's IP changes when compose recreates it. Granting the same
# user on '%' as well keeps the install working across restarts.
grant_db_user() {
  local privileges="SELECT, UPDATE, DELETE, INSERT, CREATE, DROP, INDEX, ALTER, \
LOCK TABLES, CREATE TEMPORARY TABLES, EVENT, CREATE VIEW, SHOW VIEW, REFERENCES"
  mysql_root <<SQL || { log "WARNING: could not grant ${DB_USER}@'%'"; return 0; }
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ${privileges} ON \`${DB_CONFIGURATION}\`.* TO '${DB_USER}'@'%';
GRANT ${privileges} ON \`${DB_STORAGE}\`.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
SQL
  log "granted ${DB_USER}@'%' on ${DB_CONFIGURATION} and ${DB_STORAGE}"
}

# ─────────────────────────── install wizard ───────────────────────────
# Centreon has no CLI installer: the supported install is the web wizard, whose
# steps are plain HTTP endpoints under install/steps/. Each one stores its
# answers in install/tmp/*.json, so driving them with curl in the documented
# order is a faithful, unattended run of the same install.

# Fails the start with the wizard's own message rather than a bare HTTP code.
check_response() {
  local label=$1 body=$2
  if ! printf '%s' "$body" | php -r '
    $raw = stream_get_contents(STDIN);
    $response = json_decode($raw, true);
    if (! is_array($response)) {
        fwrite(STDERR, "unexpected response: " . substr(trim($raw), 0, 400));
        exit(1);
    }
    $errors = [];
    // Steps report "result" as 0 on success, the final one as boolean true.
    $message = $response["msg"] ?? ($response["message"] ?? "failed");
    foreach ($response as $key => $value) {
        if (in_array($key, ["use_vault", "msg", "message"], true)) {
            continue;
        }
        if ($key === "result") {
            if ($value === false || (is_numeric($value) && (int) $value !== 0)) {
                $errors[] = $message;
            }
        } elseif (is_array($value) && $value !== []) {
            $errors[] = $key . " -> " . implode(", ", $value);
        } elseif ($value === false) {
            $errors[] = $key . " check failed";
        } elseif ($key === "connection" && is_string($value) && trim($value) !== "") {
            $errors[] = strip_tags($value);
        }
    }
    if ($errors !== []) {
        fwrite(STDERR, implode("; ", $errors));
        exit(1);
    }
  ' 2> /tmp/centreon-install-error; then
    die "install step '${label}' failed: $(cat /tmp/centreon-install-error)"
  fi
  log "install step '${label}' ok"
}

wizard_post() {
  local label=$1 script=$2
  shift 2
  local body
  body=$(curl -sS -m 900 -b "$COOKIE_JAR" -c "$COOKIE_JAR" \
    -X POST "$INSTALL_URL/steps/process/${script}" "$@") \
    || die "install step '${label}' could not be reached"
  check_response "$label" "$body"
}

# Steps 3 and 4 post the engine/broker paths. Their fields and defaults live in
# install/var/{engines,brokers}/*, overridden by the packaged paths in
# install/tmp/configuration.json — the same resolution the wizard's own form does.
declare -A BASE_CONF=()

load_base_conf() {
  local key value
  while IFS='=' read -r key value; do
    [ -n "$key" ] && BASE_CONF["$key"]=$value
  done < <(php -r '
    $configuration = json_decode(file_get_contents($argv[1]), true) ?: [];
    foreach ($configuration as $key => $value) {
        if (is_string($value)) {
            echo $key, "=", $value, "\n";
        }
    }
  ' "$INSTALL_DIR/tmp/configuration.json")
}

wizard_post_paths() {
  local label=$1 script=$2 definitions=$3
  local -a args=()
  local key rest name default
  # `|| [ -n "$line" ]` because these files have no trailing newline, and the
  # last field is a path the generated Broker configuration needs.
  while IFS= read -r line || [ -n "$line" ]; do
    [ -n "$line" ] || continue
    case "$line" in \#*) continue ;; esac
    key=${line%%;*}
    rest=${line#*;}
    default=${rest##*;}
    name=$(printf '%s' "$key" | tr '[:upper:] ' '[:lower:]_')
    args+=(--data-urlencode "${name}=${BASE_CONF[$name]:-$default}")
  done < "$definitions"
  wizard_post "$label" "$script" "${args[@]}"
}

run_install() {
  log "no ${CENTREON_CONF} — running the Centreon install wizard"
  rm -f "$COOKIE_JAR"

  # Step 1 renders the welcome page, which is also what checks the PHP
  # prerequisites and writes install/tmp/configuration.json.
  curl -fsS -m 60 -b "$COOKIE_JAR" -c "$COOKIE_JAR" \
    "$INSTALL_URL/steps/step.php?action=stepContent" -o /tmp/centreon-step1.html \
    || die "the install wizard is not reachable on ${INSTALL_URL}"
  [ -s "$INSTALL_DIR/tmp/configuration.json" ] \
    || die "step 1 did not pass Centreon's prerequisite check: $(sed -e 's/<[^>]*>//g' /tmp/centreon-step1.html | tr -s ' \n' ' ' | head -c 500)"
  load_base_conf
  log "install step 'prerequisites' ok"

  wizard_post_paths "engine paths" process_step3.php \
    "$INSTALL_DIR/var/engines/centreon-engine"
  wizard_post_paths "broker paths" process_step4.php \
    "$INSTALL_DIR/var/brokers/centreon-broker"

  wizard_post "admin account" process_step5.php \
    --data-urlencode "admin_password=${ADMIN_PASSWORD}" \
    --data-urlencode "confirm_password=${ADMIN_PASSWORD}" \
    --data-urlencode "firstname=${ADMIN_FIRSTNAME}" \
    --data-urlencode "lastname=${ADMIN_LASTNAME}" \
    --data-urlencode "email=${ADMIN_EMAIL}"

  wizard_post "database access" process_step6.php \
    --data-urlencode "address=${DB_HOST}" \
    --data-urlencode "port=${DB_PORT}" \
    --data-urlencode "root_user=${DB_ROOT_USER}" \
    --data-urlencode "root_password=${DB_ROOT_PASSWORD}" \
    --data-urlencode "db_configuration=${DB_CONFIGURATION}" \
    --data-urlencode "db_storage=${DB_STORAGE}" \
    --data-urlencode "db_user=${DB_USER}" \
    --data-urlencode "db_password=${DB_PASSWORD}" \
    --data-urlencode "db_password_confirm=${DB_PASSWORD}"

  # Step 7: the install itself, in the order the wizard chains them.
  wizard_post "configuration files" configFileSetup.php
  wizard_post "configuration database" installConfigurationDb.php
  wizard_post "storage database" installStorageDb.php
  wizard_post "database user" createDbUser.php
  wizard_post "base configuration" insertBaseConf.php
  wizard_post "table partitioning" partitionTables.php
  wizard_post "application cache" generationCache.php

  install_modules
  # Step 9 records the statistics choice and deletes the install directory.
  wizard_post "finalization" process_step9.php --data-urlencode "send_statistics=0"

  log "Centreon installed"
}

# Modules ship as packages (license manager, plugin packs, auto-discovery…) but
# are only registered in the database when installed — step 8 of the wizard.
install_modules() {
  [ "$INSTALL_MODULES" = "true" ] || { log "CENTREON_INSTALL_MODULES=false — skipping modules"; return 0; }
  local -a args=()
  local module
  for module in "$WWW"/modules/*/; do
    module=$(basename "$module")
    [ "$module" = "*" ] && continue
    args+=(--data-urlencode "modules[]=${module}")
  done
  [ ${#args[@]} -gt 0 ] || return 0
  # Best effort: a module that refuses to install must not abort the start.
  local body
  body=$(curl -sS -m 900 -b "$COOKIE_JAR" -c "$COOKIE_JAR" \
    -X POST "$INSTALL_URL/steps/process/process_step8.php" "${args[@]}" || true)
  if printf '%s' "$body" | grep -q '"install":false'; then
    log "WARNING: some modules failed to install: $body"
  else
    log "install step 'modules' ok"
  fi
}

# The last install step deletes the wizard's directory, but that only affects
# the container it ran in — a recreated container gets the image's copy back,
# so a platform that is already installed drops it again here.
drop_install_dir() {
  [ -d "$INSTALL_DIR" ] || return 0
  rm -rf "$INSTALL_DIR"
  log "removed the install directory"
}

# ─────────────────────────── monitoring engine ───────────────────────────
# A fresh Centreon central monitors nothing: hosts normally come from plugin
# packs, which are imported from Centreon's own repository. Adding the central
# itself gives the poller — and the ETL collector — something real to report,
# the role zabbix-agent plays for Zabbix and the bundled agent for NetXMS.
bootstrap_self_monitoring() {
  [ "$MONITOR_SELF" = "true" ] || return 0
  local hosts
  hosts=$(mysql_root -N -B -e \
    "SELECT COUNT(*) FROM \`${DB_CONFIGURATION}\`.host WHERE host_register = '1'" 2>/dev/null) || return 0
  [ "$hosts" = "0" ] || return 0

  local host_name=${CENTREON_SELF_HOST_NAME:-$(hostname)}
  local clapi=(/usr/share/centreon/bin/centreon -u admin -p "$ADMIN_PASSWORD")
  {
    "${clapi[@]}" -o CMD -a add \
      -v 'check_local_ping;check;$USER1$/check_ping -H $HOSTADDRESS$ -w 3000,80% -c 5000,100% -p 3'
    "${clapi[@]}" -o HOST -a add -v "${host_name};Centreon central;127.0.0.1;;Central;"
    local parameter
    for parameter in "check_command;check_local_ping" "max_check_attempts;3" \
      "check_interval;1" "retry_check_interval;1" "check_period;24x7" \
      "active_checks_enabled;1" "notifications_enabled;0"; do
      "${clapi[@]}" -o HOST -a setparam -v "${host_name};${parameter}"
    done
  } > /tmp/centreon-bootstrap.log 2>&1 \
    && log "created the '${host_name}' host, monitored by the Central poller" \
    || log "WARNING: could not create the '${host_name}' host: $(tail -3 /tmp/centreon-bootstrap.log)"
}

# Turns the poller configuration held in the database into the files centengine
# and cbd actually read. The web UI's "Export configuration" does the same, and
# needs gorgone to reach the daemons — which is why systemctl is shimmed.
apply_poller_config() {
  [ "$APPLY_CONFIG" = "true" ] || return 0
  # Run as root: the generator chowns what it writes to the web server user,
  # and only root may do that.
  local clapi=(/usr/share/centreon/bin/centreon -u admin -p "$ADMIN_PASSWORD")
  if "${clapi[@]}" -a POLLERGENERATE -v 1 >/tmp/centreon-clapi.log 2>&1 \
    && "${clapi[@]}" -a CFGMOVE -v 1 >>/tmp/centreon-clapi.log 2>&1; then
    log "poller configuration exported to /etc/centreon-engine"
  else
    log "WARNING: exporting the poller configuration failed: $(tail -3 /tmp/centreon-clapi.log)"
  fi
}

# The CLAPI calls above boot Symfony as root, which leaves a cache the web
# server user cannot rewrite — every API call would then answer 500. The cache
# is disposable, so hand the directory back and let php-fpm rebuild it.
reset_symfony_cache() {
  rm -rf /var/cache/centreon/symfony
  chown -R centreon:centreon /var/cache/centreon
  chmod -R g+rwX /var/cache/centreon
}

start_monitoring() {
  [ "$START_MONITORING" = "true" ] || { log "CENTREON_START_MONITORING=false — web only"; return 0; }
  mkdir -p "$LOG_DIR"
  local service
  for service in cbd centengine gorgoned; do
    touch "$LOG_DIR/$service.out"
    centreon-service start "$service" | sed 's/^/[entrypoint] /'
  done
  # Surfaces whatever the daemons print in `docker compose logs centreon`.
  tail -n 0 -F "$LOG_DIR"/*.out &
}

# Centreon's password policy, enforced by the wizard's step 5: rejecting it here
# turns a cryptic install failure into a message about the variable to fix.
check_admin_password() {
  printf '%s' "$ADMIN_PASSWORD" \
    | grep -Pq '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{12,}$' \
    || die "CENTREON_ADMIN_PASSWORD is refused by Centreon's password policy: at least 12 characters, with a lower case, an upper case, a digit and one of @\$!%*?& — and no character outside that set"
}

shutdown() {
  log "stopping"
  local service
  for service in gorgoned centengine cbd centreontrapd; do
    centreon-service stop "$service" >/dev/null 2>&1 || true
  done
  apache2ctl stop 2>/dev/null || true
  exit 0
}

# ─────────────────────────── main ───────────────────────────
if [ "${1:-centreon}" = "centreon" ]; then
  trap shutdown TERM INT

  configure_php
  fix_volume_ownership
  start_php_fpm
  # Apache serves the install wizard, so it starts before anything else and
  # then simply stays up as the container's main process.
  apache2ctl -DFOREGROUND &
  APACHE_PID=$!
  wait_for_http "http://127.0.0.1/centreon/" \
    || log "WARNING: Apache is not answering on /centreon yet — continuing"

  if [ ! -f "$CENTREON_CONF" ]; then
    check_admin_password
    wait_for_db
    run_install
  else
    log "found ${CENTREON_CONF} — skipping the install wizard"
    wait_for_db
  fi

  drop_install_dir
  grant_db_user
  bootstrap_self_monitoring
  apply_poller_config
  reset_symfony_cache
  start_monitoring

  log "Centreon is up — web UI and REST API on port 80 under /centreon"
  wait "$APACHE_PID"
  exit $?
fi

exec "$@"
